language: node_js

node_js:
    - node
    - "10"
    - "8"

cache: npm

install:
    - npm install
    - npm install -g codecov

script:
    - npm run lint
    - npm run test -- --coverage
    - npm run build
    - npm run validate:sourcemaps
    - codecov

branches:
    only:
        - master
        - /^feature\/.*$/
        - /^bugfix\/.*$/
